#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l walltime=04:00:00

# This is the main file run by the brainlife.io orchestration system
#


# run the actual python code
singularity exec docker://brainlife/dipy:latest python3 main.py
